### ISSUE TITLE
Autobrake instrument minor issue

### ISSUE THREAD

**Issue by Samhaho** [Delta-Charlie-DEV/A320FENIX_AIRMANAGER#1]
Thanks DeltaCharlie for the great work. I noticed a minor issue with the Autobrake instrument. Pushing twice on the "med" autobrake button (from the Off state) turns the button in the sim to off (button is extinguished) which is the expected behavior, however the Air manager instrument button remains "on" (enlightened).

Thanks again.

Sam

**Comment by Delta-Charlie-DEV** [comment]
Hi Sam,
Problem solved ! please download latest AUTOBRK instrument (v 1.1.3), it should work fine now

**Comment by Samhaho** [comment]
Great, Many thanks.
Sam
