### ISSUE TITLE
Front Panel EFIS Right and Left

### ISSUE THREAD

**Issue by viawave77** [Delta-Charlie-DEV/A320FENIX_AIRMANAGER#2]
Hello, first of all, thank for your great work, I just test several instrument for the A320 Fenix, but I have a question, when I made my panel in air manager I put first the Panel Glareshield CPT, how can insert the image of the  PFD and ND, I traid the AltGR + Right Click, in the Sim and put them in front, but when press any key in the panels both PFD and ND goes back of the panel and I can not see them again

**Comment by Delta-Charlie-DEV** [comment]
Hi, that's not really related to my instruments, more a question about Air Manager usage.
You have to setup the panel :
- always in foreground
- transparent background
And that should be OK.
I recommend using MSFS Popout Panel Manager, it allows you to automatically export, position, and resize with precision your exported displays when you start a new flight !

**Comment by viawave77** [comment]
Excelent! My problem Solved, thank you very much! I am realy appricited
Best Regards
Italo

**Comment by Delta-Charlie-DEV** [comment]
Nice to read you sorted it out.
