### ISSUE TITLE
LVARs for ENG2 Agent 2 LEDs is misaligned for OK - OVERHEAD - center 05 - Fire panel

### ISSUE THREAD

**Issue by danielcolchete** [Delta-Charlie-DEV/A320FENIX_AIRMANAGER#4]
I believe this is the culprit, on logic.lua lines 47 and 48 the code for Agent 2 references the LVARs for Agent 1:

local lvar_eng2agent2 =           {"L:I_OH_FIRE_ENG2_AGENT1_L","num"}
local lvar_eng2agent2squib =      {"L:I_OH_FIRE_ENG2_AGENT1_U","num"}

**Comment by Delta-Charlie-DEV** [comment]
That's a bug report  I like :-)
Many thanks for spoting it and adding the correction, instrument updated :-)
As it is not a major feature I won't package a new release "just for that" although your help is very much appreciated.
