### ISSUE TITLE
Add compatibility to MSFS 2024/Air Manager 5

### ISSUE THREAD

**Issue by FillR2** [Delta-Charlie-DEV/A320FENIX_AIRMANAGER#5]
Hi Delta-Charlie,

Do you plan to add compatibility with Air Manager 5/MSFS 2024/Fenix ?

It seems it's quite simple, API calls to _msfs20_xxx_ have to be replaced by _msfs_xxx_

Thanks for taking care.

**Comment by Delta-Charlie-DEV** [comment]
Hi, yes I'll work on it when things will be more clear. 
For now, with a "by error published" beta plugin, everything works fine for me in FS 2024 with AM 4.2 with zero code change...

**Comment by FillR2** [comment]
Thanks for the answer 

Seems the Air Manager 5 beta is still there ( https://siminnovations.com/wiki/index.php/Air_Manager_desktop_BETA ) and working OK for me.

Also, my Air Manager 4.2.11 is not connecting to MSFS 2024, so it's a bit strange.

Anyway thanks for you work !

**Comment by Delta-Charlie-DEV** [comment]
I'm waiting for the 4.2.12 release, before updating the instruments. The msfs_xxx functions will be impleted in it
https://siminnovations.com/wiki/index.php/Air_Manager_Instrument_Logic_API#Microsoft_Flight_Simulator

**Comment by Delta-Charlie-DEV** [comment]
Instruments now in V2 and fully AM5 beta / AM .4.2.12 / MFS2024 compliant :-)
