### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by davidstanko2745** [Delta-Charlie-DEV/A320FENIX_AIRMANAGER#7]
I have added everything to a blank panel, and when i click show panel to start it, it doesnt actually work. All the switches like on the PACKS and ADIRS are not there either

**Comment by davidstanko2745** [comment]
hi, i am using 4.2.11, msfs 2020 and its the current instruments i believe

**Comment by Delta-Charlie-DEV** [comment]
Ok, so please re-read the readme.md, first paragraph.
In case it's not clear enough : current release package only works with AM 5.0 BETA.
If you use AM 4.2.11, you have to download the archived (pre-v2) package.

**Comment by davidstanko2745** [comment]
Thank you so much! That was the issue. Thank you very much for your help and your quick replies! Merry christmas

**Comment by Delta-Charlie-DEV** [comment]
Nice to read ! merry christmas you too
